### PR TITLE
Add ScreenPerformAction

### PR DESCRIPTION
**Pull request by makleso6**
Hi! I need pass context to ScreenContainer when open deeplinks etc.
Probably I am not found solution in lib)

Usage

```Swift
route.push(Screens.screen(), route: { pushRoute in 
  pushRoute.perfrorm(context: context)
})
```

```Swift
route.last(.container(name: name), route: {  
  $0.perfrorm(context: context.json)
})
```

### CODE REVIEW

**Comment by almazrafi** [comment]
Hello 👋 

Could you please provide more details of using this action?
It seems that here you can pass the context as a property of the `Screen` type:

``` swift
route.push(Screens.screen(context: context))
```

**Comment by almazrafi** [comment]
> ``` swift
> route.last(.container(name: name), route: {  
>    $0.(context: context.json)
> })
> ```

The second snippet is not quite clear, what did you want to get here?

**Comment by makleso6** [comment]
My mistake, update second snippet.
Needs to pass context from deeplink on already viewed screen (selected tab/ current screen in modal)

```Swift
struct SomeDeeplink: Deeplink {
  let context: Context
  func navigate(
    screens: Screens,
    navigator: ScreenNavigator,
    handler: DeeplinkHandler
  ) throws {
    navigator.navigate(to: { route in
      return route
        .first(.tabs)
        .selectedTab {
          $0.perfrorm(context: context)
        }
    })
  }
}
```

**Comment by almazrafi** [comment]
I'm closing pull request, now you can use [ScreenGetAction](https://github.com/hhru/Nivelir/blob/main/Sources/Screen/Actions/Generic/ScreenGetAction.swift).

Thanks!

**Pull request closed without merging**
